markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
site_name: OSCAL Compass
site_url: https://oscal-compass.dev
plugins:
  - search
  - awesome-pages
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: lime
  favicon: img/oscal-compass-icon-1200x1200.png
  logo: img/oscal-logo.jpg
  font:
    text: Sen
    code: Azeret Mono
  features:
    - navigation.footer
  extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/oscal-compass
